spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/liqui?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  main:
    log-startup-info: false

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/db-changelog.yml
    rollback-file: classpath:db/rollback.yml

